name = "tobli"
main = "functions/api/[[path]].js"
compatibility_date = "2024-03-24"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "CHANGE_ME_IN_PRODUCTION"
PESAPAL_CONSUMER_KEY = ""
PESAPAL_CONSUMER_SECRET = ""
PESAPAL_URL = "https://cyb.pesapal.com/pesapalv3"

[[d1_databases]]
binding = "DB"
database_name = "tobli-db"
database_id = "8f3a3e6b-07b9-4f7d-94e8-46603a746561" # Example ID for local dev
migrations_dir = "migrations"
